---
title: "Idrott och luftvägarna"
author: "Nikolai Stenfors"
date: '2018-10-25'
output:
  #bookdown::gitbook: default
  #bookdown::pdf_book: default
  bookdown::pdf_document2
site: bookdown::bookdown_site
documentclass: book
bibliography: [references.bib]
csl: the-lancet.csl
link-citations: yes
---
# Förord
Detta är en populärvetenskaplig bok och vägledning för vuxna idrottare med luftvägsbesvär. Boken är tänkt att vara ett "levande dokument" som uppdateras fortlöpande. Lämna gärna synpunkter på eller önskemål om innehållet.  
Östersund, 2018-10-25,      
Nikolai Stenfors  
nikolai.stenfors@umu.se   

# Om författaren
Jag jobbar som universitetslektor och docent vid [Enheten för Medicin, Institutionen för folkhälsa och klinisk medicin, Umeå Universitet](https://www.umu.se/personal/nikolai-stenfors/)  där jag bl.a. undervisar om lungsjukdomar på [Läkarprogrammet](https://www.umu.se/utbildning/program/lakarprogrammet) och forskar kring luftvägseffekter av fysisk aktivitet i kyla.    
Jag jobbar även som överläkare vid [Lungmottagningen Östersunds sjukhus](https://www.1177.se/Jamtland-Harjedalen/Hitta-vard/Jamtland/Kontakt/Lung-och-allergimottagningen/?ar=True) och gör sporadiskt inlägg på [Twitter](https://twitter.com/StenforsN).

# För idrottare

## Introduktion
Alla luftvägsbesvär behöver inte vara symtom på sjukdom. Är besvären från luftvägarna lindriga, snabbt övergående, sporadiska och inte påverkar prestationsförmågan tycker kan man avvakta med att kontakta sjukvården.  Det är lätt och lockade att försöka hitta en koppla sina luftvägsbesvär med yttre omständigheter. Att föra en symtom-dagbok kan vara ett bra sätt att se om den kopplingen är konsekvent och inte slumpmässig.

## Hosta
Ansträngningsutlöst hosta är vanligt förekommande bland fysisk aktivtet i kyla. Det kan vara svårt att avgöra hostan är luftvägarnas naturliga protest mot överbelastning eller tecken på luftvägssjukdom, exvis luftvägsinfektion.

## Astma  
Astma är en kronisk inflammatorisk luftvägssjukdom som förekommer hos cirka 9% av Sveriges befolkning [ @loetvall-2009-west-sweden]. Individer med astma har överkänsliga (hyperreaktiva) luftrör som leder till återkommande episoder av luftrörsförträngning med pipande andning, tryck över bröstet, hosta och andfåddhet. Luftrörskrampen hävs spontant eller med hjälp av luftrörsvidgande inhalationsläkemedel. **Ansträngningsutlöst astma** innebär akut övergående luftrörssammandragning i samband med fysisk ansträngning och är mycket vanligt hos personer med astma.  
God kunskap om sjukdomen leder till bättre kontroll av sjukdomen och mindre besvär. Du kan läsa mer om sjukdomen på [1177 Vårdguiden](https://www.1177.se/Jamtland-Harjedalen/Fakta-och-rad/Sjukdomar/Astma/), [Hjärt-Lungfonden](https://www.hjart-lungfonden.se/Sjukdomar/Lungsjukdomar/Astma/) och [Läkemedelsverket](https://lakemedelsverket.se/malgrupp/Allmanhet/Behandlingsrekommendationerna/Behandlingsrekommendationer-A-O/Behandlingsrekommendationer---listan/Astma/).


### Läkemedel vid astma

En bra vägledning kring astmamediciner finns på [Läkemedelsverkets hemsida](https://lakemedelsverket.se/malgrupp/Allmanhet/Behandlingsrekommendationerna/Behandlingsrekommendationer-A-O/Behandlingsrekommendationer---listan/Astma/). Det är viktigt att läkemedelsbehandling utvärderas regelbundet (1-2 gånger per år) för se över graden av astmakontroll, dosering och eventuella biverkningar av läkemedlen, inhalationsteknik osv.   

### Värmeväxlare/andningmasker
Värmeväxlande andningmasker minskar effektiv ansträngningsutlöst astma vid träning i kyla eller låg luftfuktighet. 
En studie har visat att de kan vara lika effektiva som luftrörsvidgande astmamedicin [@millqvist-2000-combin-with]. Det finns många friska idrottare utan astma som upplever att det är behagligt att använda värmeväxlande andningmasker vid träning i kyla. Det finns däremot inga studier som undersökt om Värmeväxlande andningmasker kan förebygga astma hos friska skidåkare.    

### Uppvärmning
Hos individer med astma kan en uppvärmning mha 8-10 x 30 sekunders högintensiva intervaller kan förebygga ansträngningsutlöst astma. Effekten varar drygt en timme. En kontinuerlig låg-medelintensiv uppvärming utan intervaller ("jogga runt i en kvart") har ingen förebyggande effekt[@stickland-2012-effec-warm].     

## Luftvägsinfektioner
Det finns studier på att hård fysisk träning ger en övergående försämring av kroppens immunförsvar. Denna nedsättning i immunförsvaret leder inte alltid till en infektion. Många hävdar att elitidrott kräver ett starkt immunförsvar för att motstå den hårda påfrestningen på kroppen och att därför kan elitidrottare i allmänhet anses ha ett bra immunförsvar.  
Det är komplicerat att vetenskapligt studera och bevisa sambandet mellan hård fysisk träning och infektioner. De är inte alltid idrottare med symtom på infektion uppvisar några objektiva tecken eller bevis på infektion, framförallt virus (sällan bakterier) kan påvisas i endast ca 30% av idrottare med symtom.   
Under vinter-OS i Sochi 2014 blev 14% av idrottarna skadade och 8% sjuka. Av de som blev sjuka utgörde 64% problem från luftvägarna, varav 58% utgjordes av luftvägsinfektioner [@soligard15]. Deltagare i Tour de Ski har en 3 gånger ökad risk att drabbas av luftvägsinfektion jämfört med skidåkare som inte deltar i touren [@svendsen2015]. Norska elitskidåkare har i medeltal 3 luftvägsinfektioner/år som varar i medeltal 5 dagar. Flygresor och tävling innebär en ökad risk för luftvägsinfektioner [@svendsen2016].



## EILO 
Ansträngnings-utlöst kramp i luftstrupen (EILO; exercise-induced laryngeal obstruction) är en sjukdom som uppmärksammats allt mer senaste åren. 
EILO innebär att kraftig ansträning och ventilation medför en kollaps av vävnader ovan stämbandsplanet eller en paradoxal slutning av stämbanden. Orksaen är okänd.
Symtomen kommer oftast *under* maximal ansträngning (exvis tävling, hårda intervaller)Idrottaren. Idrottaren får framförallt besvär med att andas in men symtomen brukar oftas gå över så gott som omedelbart efter avslutad ansträngning eller inom någon minut.
Diagnosen ställs genom [CLE](https://www.youtube.com/watch?v=nRSSyq32GM0); mha titthåls-metoden inspektera, området runt, stämbanden under maximal fysisk ansträngning på cykel eller löpband.

*** Diagnostik
-  [[file:~/nist0013@gapps.umu.se/Google%20Foto/20150923_112721.mp4][CLE]] (continuous laryngoscopy exercise test)
*** Epidemiologi
- Köpenhamn, 14–24 åringar 7,5%
- Uppsala, 12-13 åringar 5,7%
- 88 danska elitidrottare med ERRS
  - 35% EILO
  - 60% astmamediciner
  - 60% utan stöd för astma
- 148 amerikanska idrottare med ERRS
  - 52% EIB
  - 17% astma
  - 70% VCD
*** Behandling
- Information
- Andningsövningar
- Logoped
- Operation/supraglottoplastik
*** Prognos
- God?
- "Spontanläkning"?
- 20 elitidrottande kvinnor med VCD (12-17 år)
  - Sjukdomsinformation, röst- och andningsövningar och beteendemodifikation
  - 95% fick lindring
  - astmamediciner
    - före: 19 av 20
    - efter: 4 av 20 

*** Preliminära data Östersund
- 69 svenska skidåkare
  - 18 (16-33) år
  - 54% kvinnor
  - tränar 11 tim/v
  - 36% medicinerar för astma
- 24 (38%) EILO
  - 10(41%) symtomatiska
  - 17(71%) kvinnor
* 

# För sjukvårdspersonal

## Astma

### Diagnostik
Upprepade mätningar av PEF eller FEV1 under 1-2 veckor kan användas för att påvisa reversibel bronkobstruktion, ett nyckelkriterium för astma. Sensitiviteten för dessa diagnostiska test ligger på ca 50% [Referens].  
PEF mäts två gånger per dag under 1 vecka. Varje dag beräknas PEF-variabiliteten ($(bästa PEF-lägsta
PEF)/medelvärdet av dagens två mätningar)$. Efter en veckas mätningar
beräknas medelvärdet av dessa sju mätningar. Signifikant
PEF-variabilitet föreligger om medelvärdet av sju mätningar > 10%. 
En signifikant **dygns-variabilitet** anses föreligga om  PEF varierar mer än 20% inom ett dygn. För att öka sannolikheten att påvisa dygn-variabilitet rekommenderas minst 4 PEF-mätningar jämnt fördelat över ett dygn. Mätningarna bör göras över 1-2 veckor. 

FEV1 kan mätas några gånger under förslagsvis 1-2 veckor. Om bästa-sämsta FEV1 skiljer sig mer än 12% OCH 0,2 liter föreligger signifikant FEV1-variabilitet.



## Hosta
En första medicinsk bedömning av idrottare med akut eller återkommande hosta bör fokusera på de vanligaste orsakerna: astma, luftvägsinfektioner, rinosinusit och exponering för irritanter/allergen. Hos idrottare där utlösande orsak inte kunnat fastställas har flertalet olika behandlingar, fra inhalationsläkemedel, provats utan övertygande effekt [@boulet-2017-cough-athlet] 

# Tack till  
Jag vill tacka tränare och ledare vid Svenska Skidförbundet, Svenska Skidskytteförbundet och Riksidrottsgymnasierna (längdskidor, skidskytte, skidorientering, orientering) för inspiration till denna bok.


# Litteraturlista  